# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\globalNuke\python\duckTools\dsShotOpen\dsShotOpen.ui'
#
# Created: Wed Aug 14 15:02:33 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 517)
        MainWindow.setMinimumSize(QtCore.QSize(610, 517))
        MainWindow.setMaximumSize(QtCore.QSize(610, 517))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.project_L = QtGui.QLabel(self.centralwidget)
        self.project_L.setGeometry(QtCore.QRect(180, 10, 151, 16))
        self.project_L.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.project_L.setFont(font)
        self.project_L.setObjectName("project_L")
        self.projects_CB = QtGui.QComboBox(self.centralwidget)
        self.projects_CB.setGeometry(QtCore.QRect(180, 26, 211, 20))
        self.projects_CB.setMinimumSize(QtCore.QSize(150, 0))
        self.projects_CB.setObjectName("projects_CB")
        self.user_L = QtGui.QLabel(self.centralwidget)
        self.user_L.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.user_L.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.user_L.setFont(font)
        self.user_L.setObjectName("user_L")
        self.user_CB = QtGui.QComboBox(self.centralwidget)
        self.user_CB.setGeometry(QtCore.QRect(10, 26, 171, 20))
        self.user_CB.setMinimumSize(QtCore.QSize(150, 0))
        self.user_CB.setObjectName("user_CB")
        self.episode_L = QtGui.QLabel(self.centralwidget)
        self.episode_L.setGeometry(QtCore.QRect(390, 10, 151, 16))
        self.episode_L.setMaximumSize(QtCore.QSize(201, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.episode_L.setFont(font)
        self.episode_L.setObjectName("episode_L")
        self.episodes_CB = QtGui.QComboBox(self.centralwidget)
        self.episodes_CB.setGeometry(QtCore.QRect(390, 26, 221, 20))
        self.episodes_CB.setMinimumSize(QtCore.QSize(150, 0))
        self.episodes_CB.setObjectName("episodes_CB")
        self.sequence_LW = QtGui.QListWidget(self.centralwidget)
        self.sequence_LW.setGeometry(QtCore.QRect(10, 76, 65, 400))
        self.sequence_LW.setMinimumSize(QtCore.QSize(65, 400))
        self.sequence_LW.setMaximumSize(QtCore.QSize(65, 16777215))
        self.sequence_LW.setIconSize(QtCore.QSize(100, 500))
        self.sequence_LW.setObjectName("sequence_LW")
        self.seq_L_2 = QtGui.QLabel(self.centralwidget)
        self.seq_L_2.setGeometry(QtCore.QRect(10, 55, 91, 21))
        self.seq_L_2.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.seq_L_2.setFont(font)
        self.seq_L_2.setObjectName("seq_L_2")
        self.shots_LW = QtGui.QListWidget(self.centralwidget)
        self.shots_LW.setGeometry(QtCore.QRect(80, 76, 65, 400))
        self.shots_LW.setMinimumSize(QtCore.QSize(65, 400))
        self.shots_LW.setMaximumSize(QtCore.QSize(65, 16777215))
        self.shots_LW.setIconSize(QtCore.QSize(100, 500))
        self.shots_LW.setObjectName("shots_LW")
        self.seq_L_3 = QtGui.QLabel(self.centralwidget)
        self.seq_L_3.setGeometry(QtCore.QRect(80, 55, 51, 21))
        self.seq_L_3.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.seq_L_3.setFont(font)
        self.seq_L_3.setObjectName("seq_L_3")
        self.nk_LW = QtGui.QListWidget(self.centralwidget)
        self.nk_LW.setGeometry(QtCore.QRect(150, 76, 451, 400))
        self.nk_LW.setMinimumSize(QtCore.QSize(211, 400))
        self.nk_LW.setIconSize(QtCore.QSize(100, 500))
        self.nk_LW.setObjectName("nk_LW")
        self.seq_L_4 = QtGui.QLabel(self.centralwidget)
        self.seq_L_4.setGeometry(QtCore.QRect(150, 55, 121, 21))
        self.seq_L_4.setMaximumSize(QtCore.QSize(201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.seq_L_4.setFont(font)
        self.seq_L_4.setObjectName("seq_L_4")
        self.load_B = QtGui.QPushButton(self.centralwidget)
        self.load_B.setGeometry(QtCore.QRect(500, 483, 100, 23))
        self.load_B.setMinimumSize(QtCore.QSize(100, 23))
        self.load_B.setMaximumSize(QtCore.QSize(100, 23))
        self.load_B.setObjectName("load_B")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "dsShotOpen", None, QtGui.QApplication.UnicodeUTF8))
        self.project_L.setText(QtGui.QApplication.translate("MainWindow", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.user_L.setText(QtGui.QApplication.translate("MainWindow", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.episode_L.setText(QtGui.QApplication.translate("MainWindow", "Episode:", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_L_2.setText(QtGui.QApplication.translate("MainWindow", "Seq:", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_L_3.setText(QtGui.QApplication.translate("MainWindow", "Shots:", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_L_4.setText(QtGui.QApplication.translate("MainWindow", "Scripts:", None, QtGui.QApplication.UnicodeUTF8))
        self.load_B.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))

