# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:\globalNuke\python\Render\dsSubmit.ui'
#
# Created: Tue Aug 13 14:45:28 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 325)
        MainWindow.setMinimumSize(QtCore.QSize(400, 325))
        MainWindow.setMaximumSize(QtCore.QSize(800, 325))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.compName_L = QtGui.QLabel(self.centralwidget)
        self.compName_L.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.compName_L.setMinimumSize(QtCore.QSize(71, 21))
        self.compName_L.setMaximumSize(QtCore.QSize(71, 21))
        self.compName_L.setObjectName("compName_L")
        self.fileName_L = QtGui.QLabel(self.centralwidget)
        self.fileName_L.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.fileName_L.setObjectName("fileName_L")
        self.startFrame_L = QtGui.QLabel(self.centralwidget)
        self.startFrame_L.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.startFrame_L.setObjectName("startFrame_L")
        self.endFrame_L = QtGui.QLabel(self.centralwidget)
        self.endFrame_L.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.endFrame_L.setObjectName("endFrame_L")
        self.minPackage_L = QtGui.QLabel(self.centralwidget)
        self.minPackage_L.setGeometry(QtCore.QRect(60, 200, 71, 21))
        self.minPackage_L.setObjectName("minPackage_L")
        self.deleteRange_L = QtGui.QLabel(self.centralwidget)
        self.deleteRange_L.setGeometry(QtCore.QRect(10, 230, 81, 21))
        self.deleteRange_L.setObjectName("deleteRange_L")
        self.pro_L = QtGui.QLabel(self.centralwidget)
        self.pro_L.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.pro_L.setObjectName("pro_L")
        self.compName_LE = QtGui.QLineEdit(self.centralwidget)
        self.compName_LE.setGeometry(QtCore.QRect(90, 50, 301, 21))
        self.compName_LE.setObjectName("compName_LE")
        self.fileName_LE = QtGui.QLineEdit(self.centralwidget)
        self.fileName_LE.setGeometry(QtCore.QRect(90, 80, 301, 21))
        self.fileName_LE.setObjectName("fileName_LE")
        self.startFrame_LE = QtGui.QLineEdit(self.centralwidget)
        self.startFrame_LE.setGeometry(QtCore.QRect(90, 140, 91, 21))
        self.startFrame_LE.setObjectName("startFrame_LE")
        self.endFrame_LE = QtGui.QLineEdit(self.centralwidget)
        self.endFrame_LE.setGeometry(QtCore.QRect(90, 170, 91, 21))
        self.endFrame_LE.setObjectName("endFrame_LE")
        self.minPackage_LE = QtGui.QLineEdit(self.centralwidget)
        self.minPackage_LE.setGeometry(QtCore.QRect(90, 200, 91, 21))
        self.minPackage_LE.setObjectName("minPackage_LE")
        self.deleteRange_CB = QtGui.QComboBox(self.centralwidget)
        self.deleteRange_CB.setGeometry(QtCore.QRect(90, 230, 91, 22))
        self.deleteRange_CB.setObjectName("deleteRange_CB")
        self.deleteRange_CB.addItem("")
        self.deleteRange_CB.addItem("")
        self.deleteRange_CB.addItem("")
        self.ok_B = QtGui.QPushButton(self.centralwidget)
        self.ok_B.setGeometry(QtCore.QRect(90, 290, 75, 31))
        self.ok_B.setObjectName("ok_B")
        self.cancel_B = QtGui.QPushButton(self.centralwidget)
        self.cancel_B.setGeometry(QtCore.QRect(170, 290, 75, 31))
        self.cancel_B.setObjectName("cancel_B")
        self.deleteRange_LE = QtGui.QLineEdit(self.centralwidget)
        self.deleteRange_LE.setEnabled(False)
        self.deleteRange_LE.setGeometry(QtCore.QRect(190, 230, 191, 21))
        self.deleteRange_LE.setObjectName("deleteRange_LE")
        self.priority_CB = QtGui.QComboBox(self.centralwidget)
        self.priority_CB.setGeometry(QtCore.QRect(90, 260, 91, 22))
        self.priority_CB.setObjectName("priority_CB")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.priority_CB.addItem("")
        self.initals_L = QtGui.QLabel(self.centralwidget)
        self.initals_L.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.initals_L.setMinimumSize(QtCore.QSize(71, 21))
        self.initals_L.setMaximumSize(QtCore.QSize(71, 21))
        self.initals_L.setTextFormat(QtCore.Qt.AutoText)
        self.initals_L.setObjectName("initals_L")
        self.initals_LE = QtGui.QLineEdit(self.centralwidget)
        self.initals_LE.setGeometry(QtCore.QRect(90, 20, 91, 21))
        self.initals_LE.setObjectName("initals_LE")
        self.frameFormat_L = QtGui.QLabel(self.centralwidget)
        self.frameFormat_L.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.frameFormat_L.setMinimumSize(QtCore.QSize(81, 21))
        self.frameFormat_L.setMaximumSize(QtCore.QSize(81, 21))
        self.frameFormat_L.setObjectName("frameFormat_L")
        self.frameFormat_LE = QtGui.QLineEdit(self.centralwidget)
        self.frameFormat_LE.setEnabled(False)
        self.frameFormat_LE.setGeometry(QtCore.QRect(90, 110, 301, 21))
        self.frameFormat_LE.setObjectName("frameFormat_LE")
        self.maxPackage_L = QtGui.QLabel(self.centralwidget)
        self.maxPackage_L.setGeometry(QtCore.QRect(190, 200, 71, 21))
        self.maxPackage_L.setObjectName("maxPackage_L")
        self.maxPackage_LE = QtGui.QLineEdit(self.centralwidget)
        self.maxPackage_LE.setGeometry(QtCore.QRect(220, 200, 91, 21))
        self.maxPackage_LE.setObjectName("maxPackage_LE")

        self.retranslateUi(MainWindow)
        self.priority_CB.setCurrentIndex(3)
        QtCore.QObject.connect(self.cancel_B, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.ok_B, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.initals_LE, self.compName_LE)
        MainWindow.setTabOrder(self.compName_LE, self.fileName_LE)
        MainWindow.setTabOrder(self.fileName_LE, self.frameFormat_LE)
        MainWindow.setTabOrder(self.frameFormat_LE, self.startFrame_LE)
        MainWindow.setTabOrder(self.startFrame_LE, self.endFrame_LE)
        MainWindow.setTabOrder(self.endFrame_LE, self.minPackage_LE)
        MainWindow.setTabOrder(self.minPackage_LE, self.maxPackage_LE)
        MainWindow.setTabOrder(self.maxPackage_LE, self.deleteRange_CB)
        MainWindow.setTabOrder(self.deleteRange_CB, self.deleteRange_LE)
        MainWindow.setTabOrder(self.deleteRange_LE, self.priority_CB)
        MainWindow.setTabOrder(self.priority_CB, self.ok_B)
        MainWindow.setTabOrder(self.ok_B, self.cancel_B)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "dsSubmitter", None, QtGui.QApplication.UnicodeUTF8))
        self.compName_L.setText(QtGui.QApplication.translate("MainWindow", "Comp Name", None, QtGui.QApplication.UnicodeUTF8))
        self.fileName_L.setText(QtGui.QApplication.translate("MainWindow", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrame_L.setText(QtGui.QApplication.translate("MainWindow", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrame_L.setText(QtGui.QApplication.translate("MainWindow", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.minPackage_L.setText(QtGui.QApplication.translate("MainWindow", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRange_L.setText(QtGui.QApplication.translate("MainWindow", "Delete Range", None, QtGui.QApplication.UnicodeUTF8))
        self.pro_L.setText(QtGui.QApplication.translate("MainWindow", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.minPackage_LE.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRange_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRange_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRange_CB.setItemText(2, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_B.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_B.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRange_LE.setText(QtGui.QApplication.translate("MainWindow", "1-100", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(0, QtGui.QApplication.translate("MainWindow", "DOITNOW", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(1, QtGui.QApplication.translate("MainWindow", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(2, QtGui.QApplication.translate("MainWindow", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(3, QtGui.QApplication.translate("MainWindow", "75", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(4, QtGui.QApplication.translate("MainWindow", "70", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(5, QtGui.QApplication.translate("MainWindow", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(6, QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(7, QtGui.QApplication.translate("MainWindow", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(8, QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.priority_CB.setItemText(9, QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.initals_L.setText(QtGui.QApplication.translate("MainWindow", "Initials", None, QtGui.QApplication.UnicodeUTF8))
        self.frameFormat_L.setText(QtGui.QApplication.translate("MainWindow", "Frame Format", None, QtGui.QApplication.UnicodeUTF8))
        self.maxPackage_L.setText(QtGui.QApplication.translate("MainWindow", "max", None, QtGui.QApplication.UnicodeUTF8))
        self.maxPackage_LE.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))

